export enum UserRole {
  CUSTOMER = 'CUSTOMER',
  VENDOR = 'VENDOR',
  ADMIN = 'ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum KYCStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum VendorTier {
  SOLO = 'SOLO',
  MASTER = 'MASTER',
  ADVANCED = 'ADVANCED',
}

export enum DocType {
  TRADE_LICENSE = 'TRADE_LICENSE',
  IDENTITY = 'IDENTITY',
  BUSINESS_REGISTRATION = 'BUSINESS_REGISTRATION',
  TAX_CERTIFICATE = 'TAX_CERTIFICATE',
}

export enum DocStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum ProductType {
  SHEESHA_PIPE = 'SHEESHA_PIPE',
  TOBACCO_BLEND = 'TOBACCO_BLEND',
  ACCESSORY = 'ACCESSORY',
  RENTAL_PACKAGE = 'RENTAL_PACKAGE',
  EQUIPMENT = 'EQUIPMENT',
}

export enum OrderStatus {
  PREPARING = 'PREPARING',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  ACTIVE_RENTAL = 'ACTIVE_RENTAL',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum SettlementStatus {
  PENDING = 'PENDING',
  PROCESSED = 'PROCESSED',
  PAID = 'PAID',
  FAILED = 'FAILED',
}
